import type { Block } from 'payload'

export const formBlock: Block = {
  slug: 'form',
  labels: {
    singular: 'Konzultációs űrlap szekció',
    plural: 'Konzultációs űrlap szekciók',
  },
  fields: [
    {
      name: 'showHeader',
      label: 'Szekció fejléce megjelenjen?',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      name: 'heading',
      label: 'Szekció címe',
      type: 'text',
      required: false,
      admin: {
        condition: (_, siblingData) => Boolean(siblingData.showHeader),
      },
    },
    {
      name: 'lead',
      label: 'Alcím',
      type: 'text',
      required: false,
      admin: {
        condition: (_, siblingData) => Boolean(siblingData.showHeader),
      },
    },
    {
      name: 'description',
      label: 'Leírás',
      type: 'textarea',
      required: false,
      admin: {
        condition: (_, siblingData) => Boolean(siblingData.showHeader),
      },
    },
    {
      name: 'image',
      label: 'Háttérkép',
      type: 'upload',
      relationTo: 'media',
      required: true,
    },
    {
      name: 'lastNameLabel',
      label: 'Vezetéknév címke',
      type: 'text',
      required: true,
      defaultValue: 'Vezetéknév',
    },
    {
      name: 'lastNameHint',
      label: 'Vezetéknév kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(kötelező)',
    },
    {
      name: 'lastNamePlaceholder',
      label: 'Vezetéknév helyettesítő szöveg',
      type: 'text',
      required: false,
    },
    {
      name: 'firstNameLabel',
      label: 'Keresztnév címke',
      type: 'text',
      required: true,
      defaultValue: 'Keresztnév',
    },
    {
      name: 'firstNameHint',
      label: 'Keresztnév kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(kötelező)',
    },
    {
      name: 'firstNamePlaceholder',
      label: 'Keresztnév helyettesítő szöveg',
      type: 'text',
      required: false,
    },
    {
      name: 'emailLabel',
      label: 'Email címke',
      type: 'text',
      required: true,
      defaultValue: 'Email',
    },
    {
      name: 'emailHint',
      label: 'Email kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(kötelező)',
    },
    {
      name: 'emailPlaceholder',
      label: 'Email helyettesítő szöveg',
      type: 'text',
      required: false,
    },
    {
      name: 'phoneLabel',
      label: 'Telefonszám címke',
      type: 'text',
      required: true,
      defaultValue: 'Telefonszám',
    },
    {
      name: 'phoneHint',
      label: 'Telefonszám kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(opcionális)',
    },
    {
      name: 'phonePlaceholder',
      label: 'Telefonszám helyettesítő szöveg',
      type: 'text',
      required: false,
    },
    {
      name: 'companyLabel',
      label: 'Cégnév címke',
      type: 'text',
      required: true,
      defaultValue: 'Cégnév',
    },
    {
      name: 'companyHint',
      label: 'Cégnév kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(opcionális)',
    },
    {
      name: 'companyPlaceholder',
      label: 'Cégnév helyettesítő szöveg',
      type: 'text',
      required: false,
    },
    {
      name: 'websiteLabel',
      label: 'Cég weboldala címke',
      type: 'text',
      required: true,
      defaultValue: 'Cég weboldala',
    },
    {
      name: 'websiteHint',
      label: 'Cég weboldala kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(opcionális)',
    },
    {
      name: 'websitePlaceholder',
      label: 'Cég weboldala helyettesítő szöveg',
      type: 'text',
      required: false,
    },
    {
      name: 'serviceLabel',
      label: 'Szolgáltatás címke',
      type: 'text',
      required: true,
      defaultValue: 'Miben segíthetünk?',
    },
    {
      name: 'serviceHint',
      label: 'Szolgáltatás kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(kötelező)',
    },
    {
      name: 'servicePlaceholder',
      label: 'Szolgáltatás helyettesítő szöveg',
      type: 'text',
      required: false,
      defaultValue: 'Kérünk, válassz.',
    },
    {
      name: 'messageLabel',
      label: 'Üzenet címke',
      type: 'text',
      required: true,
      defaultValue: 'Üzenet',
    },
    {
      name: 'messageHint',
      label: 'Üzenet kiegészítés',
      type: 'text',
      required: false,
      defaultValue: '(kötelező)',
    },
    {
      name: 'messagePlaceholder',
      label: 'Üzenet helyettesítő szöveg',
      type: 'text',
      required: false,
      defaultValue: 'Fejtsd ki, miben segíthetünk.',
    },
    {
      name: 'toggleLabel',
      label: 'Kapcsoló címke',
      type: 'text',
      required: false,
    },
    {
      name: 'toggleDescription',
      label: 'Kapcsoló leírás',
      type: 'textarea',
      required: false,
    },
    {
      name: 'toggleFile',
      label: 'Letölthető fájl (PDF vagy más)',
      type: 'upload',
      relationTo: 'media',
      required: false,
    },
    {
      name: 'endpoint',
      label: 'Űrlap beküldési URL',
      type: 'text',
      required: true,
    },
    {
      name: 'submitLabel',
      label: 'Küldés gomb felirata',
      type: 'text',
      required: true,
      defaultValue: 'Küldés',
    },
  ],
}
